services:
  pyright:
    image: ghcr.io/abstractumbra/pyright-api:latest
    container_name: "pyright"
    restart: unless-stopped
    ports:
      - "8130:8130"
    secrets:
      - api_key

secrets:
  api_key:
    file: ./api_key
